#!/bin/sh

export PATH=“/sw/bin:/sw/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:$PATH”

node=$(which node 2> /dev/null)
if [ "x$node" = "x" ];then
	echo "Nodejs is not installed"
	exit 1
fi
npm=$(which npm 2> /dev/null)
if [ "xnpm" = "x" ];then
    echo "npm is not installed"
fi

i=0
cur=""
cd $(dirname $0)
while [ "x$cur" = "x" ] && [ "$cur" != "/" ] && [ $i -lt 5 ]
do
    cur=$(ls | grep 'server.*js')
    if [ "x$cur" = "x" ];then
        cd ../
    fi
    i=$((i+1))
done

if [ "x$cur" = "x" ];then
    err=$(npm list -g snmpsniffer 1> /dev/null)
    if [ -n "$err" ];then
        echo "The library is not installed"
        exit 1
    fi
    lib=$(npm list -g snmpsniffer | head -n1)
    export SNMPSNIFFER_HOME="$lib/node_modules/snmpsniffer"
    cd $SNMPSNIFFER_HOME
fi

echo "Wait, the application is starting..."

serv=$(ls | grep 'server.min.js')
if [ "x$serv" = "x" ];then
	serv=$(ls | grep 'server.js')
fi

node $serv $*


