#!/bin/sh

curr=$(pwd | grep '/installers/linux$')
if [ "x$curr" != "x" ]; then  cd ../../;fi
prefix=$(which node 2>/dev/null | sed "s|/bin/.*|/bin|")
if [ "x$prefix" = "x" ]; then
	echo "Nodejs is not installed"
	exit 1
else
	versionshort=$(node --version | sed -r 's|^v0\.([0-9]+)\.([0-9]+)|\1|'| bc)
	if [ $versionshort -lt 12 ]; then
		echo "Your Nodejs version is $versionshort. The application required Nodejs version 0.12 or above, please, update your version."
		exit 1
	fi
fi

if [ -f /etc/debian_version ] || [ -f /etc/fedora_release ]; then app_prefix="/usr/local"; else app_prefix="/usr"; fi


echo "Installing packages..."
if [ -w $prefix ];then
	NODE_ENV=production "$prefix/npm" install -g
	echo "Create node global symlink..."
        sudo ln -s -f "$prefix/node" $app_prefix/bin/node
        echo "Create npm global symlink..."
        sudo ln -s -f "$prefix/npm" $app_prefix/bin/npm 
else
	sudo NODE_ENV=production "$prefix/npm" install -g
fi

echo "Checking the application data directory..."
if [ ! -d "$HOME/.snmpsniffer/config"  ]; then
	mkdir -p "$HOME/.snmpsniffer/config"
	cp -R files/config/config.txt "$HOME/.snmpsniffer/config"
	if [ ! -d "$HOME/.snmpsniffer/license" ]; then mkdir "$HOME/.snmpsniffer/license"; fi
	mkdir -p "$HOME/.snmpsniffer/log"
fi

echo "Creating a launcher..."
if [ -w $prefix ];then
	cp -f "bin/linux/snmpsniffer" "$prefix/snmpsniffer"
        echo "Create snmpsniffer global symlink..."
        sudo ln -s -f "$prefix/snmpsniffer" $app_prefix/bin/snmpsniffer
else
	sudo cp -f "bin/linux/snmpsniffer" "$prefix/snmpsniffer"
fi

sudo chmod 755 "$prefix/snmpsniffer"

echo "Copying icons..."

xdg-icon-resource install --novendor --size 16 icons/snmp_sniffer16x16.png snmpsniffer
xdg-icon-resource install --novendor --size 22 icons/snmp_sniffer22x22.png snmpsniffer
xdg-icon-resource install --novendor --size 24 icons/snmp_sniffer24x24.png snmpsniffer
xdg-icon-resource install --novendor --size 32 icons/snmp_sniffer32x32.png snmpsniffer
xdg-icon-resource install --novendor --size 48 icons/snmp_sniffer48x48.png snmpsniffer
xdg-icon-resource install --novendor --size 64 icons/snmp_sniffer64x64.png snmpsniffer
xdg-icon-resource install --novendor --size 128 icons/snmp_sniffer128x128.png snmpsniffer
xdg-icon-resource install --novendor --size 256 icons/snmp_sniffer256x256.png snmpsniffer

echo "Creating an application menu item..."
if [ ! -d "$app_prefix/share/applications" ]; then sudo mkdir -p "$app_prefix/share/applications"; fi
sudo cp -f "bin/linux/snmpsniffer.desktop" "$app_prefix/share/applications"
xdg-desktop-menu install --novendor "$app_prefix/share/applications/snmpsniffer.desktop"


echo "Installation finished"







