#!/bin/sh

install_prefix="$1"
curr=$(pwd | grep '/installers/linux$')
if [ "x$curr" != "x" ]; then  cd ../../;fi
node=$(ls | grep "^node$\|^node-..*")
if [ ! -z $node ] && [ -d $node ]; then
	reinstall="Y"
	nodeinstalled=$(command -v node)
	if [ ! -z $nodeinstalled ]; then
	        reinstall="N"
		version=$(node --version)
		echo "Nodejs, version $version, is already installed. Would you like to reinstall Nodejs Y/N [N]?"
		read reinstall
	fi
	if [ $reinstall = "Y" ] || [ $reinstall = 'y' ]; then
		if [ "x$install_prefix" = "x" ]; then 
			if [ -f /etc/debian_version ] || [ -f /etc/fedora_release ]; then install_prefix="/usr/local"; else install_prefix="/usr"; fi
		elif [ -f /etc/debian_version ] && [ $install_prefix!="/usr/local" ] && [ $install_prefix!="/usr" ]; then 
			echo "Bad installation directory, only /usr and /usr/local are allowed"
			exit 1
		elif [ $install_prefix!="/usr" ]; then 
			echo "Bad installation directory. The installation directory will be set to /usr"
			install_prefix="/usr"
		fi		
		cd $node
		sudo cp -fr bin/* "$install_prefix/bin"
		sudo cp -fr lib/* "$install_prefix/lib"
		mandir="$install_prefix/share/man/man1"
		if [ ! -d $mandir ]; then sudo mkdir -p "$mandir"; fi
		sudo cp -fr share/man/man1/* "$mandir"
		cd "../" 
		echo "Nodejs installed"
	fi
fi
prefix=$(which node 2>/dev/null | sed "s|/bin/.*||")
echo "prefix $prefix"
dir="$prefix/lib/node_modules/snmpsniffer"
if [ "x$prefix" = "x" ]; then
	echo "Nodejs is not installed"
	exit 1
else
	versionshort=$(node --version | sed -r 's|^v0\.([0-9]+)\.([0-9]+)|\1|'| bc)
	if [ $versionshort -lt 10 ]; then
		echo "Your Nodejs version is $version10. The application required Nodejs version 0.10 or above, please, update your version."
		exit 1
	fi
fi
echo "Installing packages..."
sudo "$prefix/bin/npm" install -g

echo "Checking the application data directory..."
if [ ! -d "$HOME/.snmpsniffer/config"  ]; then
	mkdir -p "$HOME/.snmpsniffer/config"
	cp -R $dir/files/config/config.txt "$HOME/.snmpsniffer/config"
	if [ ! -d "$HOME/.snmpsniffer/license" ]; then mkdir "$HOME/.snmpsniffer/license"; fi
	mkdir -p "$HOME/.snmpsniffer/log"
fi

echo "Creating a launcher..."
sudo mv -f "$dir/snmpsniffer" "$prefix/bin/snmpsniffer"
sudo chmod 755 "$prefix/bin/snmpsniffer"

echo "Copying icons..."

xdg-icon-resource install --novendor --size 16 icons/snmp_sniffer16x16.png snmpsniffer
xdg-icon-resource install --novendor --size 22 icons/snmp_sniffer22x22.png snmpsniffer
xdg-icon-resource install --novendor --size 24 icons/snmp_sniffer24x24.png snmpsniffer
xdg-icon-resource install --novendor --size 32 icons/snmp_sniffer32x32.png snmpsniffer
xdg-icon-resource install --novendor --size 48 icons/snmp_sniffer48x48.png snmpsniffer
xdg-icon-resource install --novendor --size 64 icons/snmp_sniffer64x64.png snmpsniffer
xdg-icon-resource install --novendor --size 128 icons/snmp_sniffer128x128.png snmpsniffer
xdg-icon-resource install --novendor --size 256 icons/snmp_sniffer256x256.png snmpsniffer

echo "Creating an application menu item..."
if [ ! -d "$prefix/share/applications" ]; then sudo mkdir "$prefix/share/applications"; fi
sudo mv -f "$dir/snmpsniffer.desktop" "$prefix/share/applications"
xdg-desktop-menu install --novendor "$prefix/share/applications/snmpsniffer.desktop"
echo "Installation finished"







